/**
 * Regenerates docs/screenshots/*.png and docs/screenshots/INDEX.md: every page in a meaningful
 * state against throwaway fake machines (browser mode, real server), 380x640 light by default,
 * a few in dark, one at 320 px and some at 1280x800.
 *
 *   pnpm build && cargo build -p sweep-cli --features testutil && pnpm screenshots
 */
import { test, expect, type Browser, type Page } from '@playwright/test';
import { mkdirSync, symlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { callApi, resetSandbox, startServer, type ServerInfo } from '../tests/e2e/fixtures';
import { startFakeMachine, type FakeMachine } from '../tests/e2e/helpers/fakeSystem';
import { bootMachine, type StartupMachine } from '../tests/e2e/helpers/startupMachine';

const OUT = path.resolve(import.meta.dirname, '../docs/screenshots');
mkdirSync(OUT, { recursive: true });

interface Shot {
  file: string;
  caption: string;
  size: string;
  theme: string;
}
const shots: Shot[] = [];

interface View {
  w?: number;
  h?: number;
  scheme?: 'light' | 'dark';
}

test.describe.configure({ mode: 'serial' });

let main: { info: ServerInfo; stop: () => Promise<void> };
let startup: StartupMachine;
let fake: FakeMachine;

function put(file: string, content: string | Buffer): void {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
}

test.beforeAll(async () => {
  main = await startServer();
  startup = await bootMachine(
    (m) => {
      put(path.join(m.autostartDir, 'slack.desktop'), '[Desktop Entry]\nType=Application\nName=Slack\nExec=/opt/Slack/slack -u %U\n');
      put(path.join(m.autostartDir, 'a-rather-long-named-application-that-starts-automatically.desktop'), '[Desktop Entry]\nType=Application\nName=A Rather Long Named Application That Starts Automatically With The Desktop\nExec=/opt/vendor/long/app --flag\n');
      put(m.sys('/etc/xdg/autostart/blueman.desktop'), '[Desktop Entry]\nType=Application\nName=Blueman Applet\nExec=blueman-applet\n');
      m.writeState('user-units.txt', 'syncthing.service enabled\npipewire.service enabled\n');
      m.writeState('system-units.txt', 'ssh.service enabled\nmyapp.service enabled\n');
      m.writeState('crontab', '# my jobs\n@reboot /home/u/bin/sync.sh --quiet\n');
    },
    {
      processes:
        'slack|/opt/Slack/slack|300|3,slack|/opt/Slack/slack|120|1,gnome-shell|/usr/bin/gnome-shell|400|2,a-very-long-application-name-that-keeps-going-and-going-and-going|/opt/vendor/directory/with/a/deep/path/bin/app|250|3',
    },
  );
  fake = await startFakeMachine();
  fake.writeState(
    'dpkg.txt',
    [
      'bash\t5.2.21\t1844\tUbuntu Developers <dev@example.com>\trequired\tyes\tinstalled',
      'clearsweep-demo\t1.0.0\t120\tDemo Maker <demo@example.com>\toptional\t\tinstalled',
      'htop\t3.3.0\t400\tSomeone <s@example.com>\toptional\t\tinstalled',
      'libreoffice-writer-with-an-exceptionally-long-package-name-for-layout-testing\t24.2.1\t88000\tThe Document Foundation <tdf@example.com>\toptional\t\tinstalled',
    ].join('\n') + '\n',
  );
});

test.afterAll(async () => {
  await main?.stop();
  await startup?.stop();
  await fake?.stop();
  const rows = shots.map((s) => `| \`${s.file}\` | ${s.size} | ${s.theme} | ${s.caption} |`).join('\n');
  writeFileSync(
    path.join(OUT, 'INDEX.md'),
    `# ClearSweep screenshots

Generated by \`pnpm screenshots\` (\`scripts/screenshots.ts\`) in browser mode against throwaway fake machines.
Default: 380x640, light theme.

| File | Size | Theme | What it shows |
| --- | --- | --- | --- |
${rows}
`,
  );
});

async function scene(browser: Browser, server: ServerInfo, hash: string, view: View, fn: (page: Page) => Promise<void>): Promise<void> {
  const ctx = await browser.newContext({ viewport: { width: view.w ?? 380, height: view.h ?? 640 }, colorScheme: view.scheme ?? 'light' });
  const page = await ctx.newPage();
  try {
    await page.goto(`${server.url}#${hash}`);
    await expect(page.getByTestId('appbar-title')).toBeVisible();
    await fn(page);
  } finally {
    await ctx.close();
  }
}

async function shoot(page: Page, name: string, caption: string, view: View = {}): Promise<void> {
  const theme = view.scheme ?? 'light';
  const prefix = view.w && view.w >= 900 ? 'wide-' : view.scheme === 'dark' ? 'dark-' : view.w === 320 ? 'w320-' : '';
  const file = `${prefix}${name}.png`;
  await page.waitForTimeout(250); // let transitions settle
  await page.screenshot({ path: path.join(OUT, file) });
  shots.push({ file, caption, size: `${view.w ?? 380}x${view.h ?? 640}`, theme });
}

const dark: View = { scheme: 'dark' };
const wide: View = { w: 1280, h: 800 };

async function scanHome(page: Page): Promise<void> {
  await page.getByTestId('btn-scan').click();
  await expect(page.getByTestId('cat-security')).toBeVisible();
  await expect(page.getByTestId('btn-scan')).toBeEnabled();
}

async function analyzeClean(page: Page): Promise<void> {
  await page.getByTestId('btn-analyze').click();
  await expect(page.getByTestId('btn-clean')).toBeEnabled();
}

test('home and findings', async ({ browser }) => {
  await scene(browser, main.info, '/', {}, async (p) => {
    await shoot(p, 'home-before-scan', 'Home before the first scan');
    await scanHome(p);
    await shoot(p, 'home-scanned', 'Home after a scan: score ring and category cards');
    const card = p.locator('[data-testid^="cat-"]:not([data-testid$="-status"]):not([data-testid$="-summary"])').first();
    await card.click();
    await shoot(p, 'home-findings-sheet', 'A category opened as a bottom sheet');
  });
  await scene(browser, main.info, '/', dark, async (p) => {
    await scanHome(p);
    await shoot(p, 'home-scanned', 'Home after a scan', dark);
  });
  await scene(browser, main.info, '/', wide, async (p) => {
    await scanHome(p);
    await shoot(p, 'home-scanned', 'Wide layout: navigation rail and a 720 px content column', wide);
  });
});

test('clean', async ({ browser }) => {
  await scene(browser, main.info, '/clean', {}, async (p) => {
    await shoot(p, 'clean-rules', 'Clean: rules grouped by application');
    await analyzeClean(p);
    await shoot(p, 'clean-analyzed', 'Clean after Analyze (top of the list)');
    await p.getByTestId('btn-clean').click();
    await shoot(p, 'clean-confirm', 'Clean: confirmation sheet');
  });
  await scene(browser, main.info, '/clean', dark, async (p) => {
    await analyzeClean(p);
    await shoot(p, 'clean-analyzed', 'Clean after Analyze', dark);
  });
});

test('tools and small pages', async ({ browser }) => {
  await scene(browser, main.info, '/tools', {}, async (p) => shoot(p, 'tools-grid', 'Tools grid'));
  await scene(browser, main.info, '/tools', { w: 320 }, async (p) => shoot(p, 'tools-grid', 'Tools grid at the narrowest width (320 px)', { w: 320 }));
  await scene(browser, main.info, '/tools', dark, async (p) => shoot(p, 'tools-grid', 'Tools grid', dark));
  await scene(browser, main.info, '/tools', wide, async (p) => shoot(p, 'tools-grid', 'Tools grid, wide layout', wide));
  await scene(browser, main.info, '/settings', {}, async (p) => {
    await expect(p.getByTestId('settings-appearance')).toBeVisible();
    await shoot(p, 'settings', 'Settings: appearance (theme, compact mode) and cleaning');
  });
  await scene(browser, main.info, '/settings', dark, async (p) => {
    await expect(p.getByTestId('settings-appearance')).toBeVisible();
    await shoot(p, 'settings', 'Settings', dark);
  });
  await scene(browser, main.info, '/settings/schedules', {}, async (p) => {
    await shoot(p, 'schedules-empty', 'Scheduled cleaning, no schedules yet');
    await p.getByTestId('schedule-add').click();
    await shoot(p, 'schedules-sheet', 'Add schedule sheet');
  });
  await scene(browser, main.info, '/tools/sysinfo', {}, async (p) => {
    await expect(p.getByTestId('sysinfo-cpu')).toBeVisible();
    await shoot(p, 'sysinfo', 'System Info');
  });
  await scene(browser, main.info, '/tools/wiper', {}, async (p) => {
    await p.locator('[data-testid^="wiper-drive-"]').first().click();
    await shoot(p, 'wiper', 'Drive Wiper with a drive selected');
  });
  await scene(browser, main.info, '/tools/registry', {}, async (p) => shoot(p, 'config-issues', 'Config Issues (registry cleaner on Windows)'));
  await scene(browser, main.info, '/tools/cookies', {}, async (p) => {
    await expect(p.locator('[data-testid^="cookie-select-"]').first()).toBeVisible();
    await shoot(p, 'cookies', 'Cookies by site');
  });
});

test('disk analyzer and duplicates', async ({ browser }) => {
  const dir = path.join(main.info.dir, 'home', 'Documents', 'photo-archive');
  put(path.join(dir, 'pics/holiday-photo-from-the-very-long-named-trip-2024-final-final-v2.jpg'), Buffer.alloc(300_000, 'a'));
  put(path.join(dir, 'pics/photo2.png'), Buffer.alloc(120_000, 'b'));
  put(path.join(dir, 'music/song.mp3'), Buffer.alloc(800_000, 'c'));
  put(path.join(dir, 'videos/clip.mkv'), Buffer.alloc(2_000_000, 'd'));
  put(path.join(dir, 'docs/report.pdf'), Buffer.alloc(50_000, 'e'));
  put(path.join(dir, 'copies/clip-copy.mkv'), Buffer.alloc(2_000_000, 'd'));
  put(path.join(dir, 'copies/song-copy.mp3'), Buffer.alloc(800_000, 'c'));
  put(path.join(dir, 'copies/song-copy-2.mp3'), Buffer.alloc(800_000, 'c'));
  symlinkSync(dir, path.join(dir, 'pics/loop'));
  const analyze = async (p: Page) => {
    await p.getByTestId('disk-folder-input').fill(dir);
    await p.getByTestId('disk-folder-input').press('Enter');
    await p.getByTestId('btn-disk-analyze').click();
    await expect(p.getByTestId('disk-categories')).toBeVisible();
  };
  await scene(browser, main.info, '/tools/disk', {}, async (p) => {
    await shoot(p, 'disk-analyzer-start', 'Disk Analyzer before a scan');
    await analyze(p);
    await shoot(p, 'disk-analyzer-scanned', 'Disk Analyzer: space by file type');
    await p.getByTestId('disk-tab-folders').click();
    await shoot(p, 'disk-analyzer-folders', 'Disk Analyzer: biggest folders');
  });
  await scene(browser, main.info, '/tools/disk', dark, async (p) => {
    await analyze(p);
    await shoot(p, 'disk-analyzer-scanned', 'Disk Analyzer: space by file type', dark);
  });
  await scene(browser, main.info, '/tools/disk', wide, async (p) => {
    await analyze(p);
    await shoot(p, 'disk-analyzer-scanned', 'Disk Analyzer, wide layout', wide);
  });
  await scene(browser, main.info, '/tools/duplicates', {}, async (p) => {
    await p.getByTestId('btn-dup-options').click();
    await p.getByTestId('dup-path-input').fill(dir);
    await p.getByTestId('dup-path-add').click();
    await shoot(p, 'duplicates-options', 'Duplicate Finder: search options sheet');
    await p.getByTestId('dup-options-done').click();
    await p.getByTestId('btn-dup-scan').click();
    await expect(p.getByTestId('dup-groups')).toBeVisible();
    await shoot(p, 'duplicates-groups', 'Duplicate Finder: groups of identical files');
  });
});

test('startup, performance, plugins', async ({ browser }) => {
  await scene(browser, startup.server, '/tools/startup', {}, async (p) => {
    await expect(p.getByTestId('startup-list')).toBeVisible();
    await shoot(p, 'startup-list', 'Startup items with on/off switches');
  });
  await scene(browser, startup.server, '/tools/startup', dark, async (p) => {
    await expect(p.getByTestId('startup-list')).toBeVisible();
    await shoot(p, 'startup-list', 'Startup items', dark);
  });
  await scene(browser, startup.server, '/performance', {}, async (p) => {
    await expect(p.getByTestId('perf-list')).toBeVisible();
    await shoot(p, 'performance-list', 'Performance: background apps that can sleep');
  });
  await scene(browser, startup.server, '/tools/plugins', {}, async (p) => shoot(p, 'browser-plugins', 'Browser Plugins'));
});

test('uninstall and updater', async ({ browser }) => {
  await scene(browser, fake.server, '/tools/uninstall', {}, async (p) => {
    await expect(p.getByTestId('uninstall-list')).toBeVisible();
    await shoot(p, 'uninstall-list', 'Uninstall: installed programs (long names wrap)');
    await p.getByTestId('app-row-dpkg:clearsweep-demo').click();
    await shoot(p, 'uninstall-sheet', 'Uninstall: program details sheet');
  });
  await scene(browser, fake.server, '/tools/updater', {}, async (p) => {
    await expect(p.getByTestId('updater-list')).toBeVisible();
    await shoot(p, 'software-updater', 'Software Updater: available updates');
  });
  await scene(browser, fake.server, '/tools/drivers', {}, async (p) => {
    await p.getByTestId('btn-scan').click();
    await expect(p.getByTestId('btn-scan')).toBeEnabled();
    await shoot(p, 'driver-updater', 'Driver Updater after a scan');
  });
});

test('file shredder', async ({ browser }) => {
  const victim = path.join(main.info.dir, 'home', 'Documents', 'old-tax-return-2019.pdf');
  put(victim, Buffer.alloc(20_000, 'x'));
  const fill = async (p: Page) => {
    await p.getByTestId('shredder-input').fill(`${victim}\n${main.info.dir}/home`);
    await p.getByTestId('shredder-add').click();
  };
  await scene(browser, main.info, '/tools/shredder', {}, async (p) => {
    await shoot(p, 'file-shredder-empty', 'File Shredder before adding paths');
    await fill(p);
    await shoot(p, 'file-shredder-paths', 'File Shredder with two paths added');
    await p.getByTestId('btn-shredder-start').click();
    await p.getByTestId('confirm-sheet-input').fill('SHRED');
    await shoot(p, 'file-shredder-confirm', 'File Shredder: type SHRED to confirm');
    await p.getByTestId('confirm-sheet-confirm').click();
    await expect(p.getByTestId('shredder-result')).toBeVisible();
    await shoot(p, 'file-shredder-result', 'File Shredder: per-path result (one shredded, one refused)');
  });
  const again = path.join(main.info.dir, 'home', 'Documents', 'second.pdf');
  put(again, Buffer.alloc(20_000, 'y'));
  await scene(browser, main.info, '/tools/shredder', dark, async (p) => {
    await p.getByTestId('shredder-input').fill(again);
    await p.getByTestId('shredder-add').click();
    await p.getByTestId('btn-shredder-start').click();
    await p.getByTestId('confirm-sheet-input').fill('SHRED');
    await shoot(p, 'file-shredder-confirm', 'File Shredder confirmation', dark);
  });
});

test('clean history, not found, sign-in page', async ({ browser }) => {
  resetSandbox(main.info.dir);
  await scene(browser, main.info, '/clean', {}, async (p) => {
    await analyzeClean(p);
    await p.getByTestId('btn-clean').click();
    await p.getByTestId('confirm-sheet-confirm').click();
    await expect(p.getByTestId('history-link')).toBeVisible();
    await shoot(p, 'clean-done', 'Clean finished: summary of what was removed');
    await p.getByTestId('history-link').click();
    await expect(p.getByTestId('page-clean-history')).toBeVisible();
    await shoot(p, 'clean-history', 'Cleaning history');
  });
  await scene(browser, main.info, '/no/such/page', {}, async (p) => shoot(p, 'not-found', 'Unknown route'));
  const ctx = await browser.newContext({ viewport: { width: 380, height: 640 } });
  const page = await ctx.newPage();
  await page.goto(main.info.origin + '/');
  await expect(page.getByTestId('page-auth-required')).toBeVisible();
  await shoot(page, 'open-from-link', 'Tab opened without the private link');
  await ctx.close();
  await callApi(main.info, 'settings.reset');
});
